// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cadastro_lojas_fullstack.Infra;

#nullable disable

namespace cadastrolojasfullstack.Migrations
{
    [DbContext(typeof(CadastroLojasContext))]
    [Migration("20221220012327_CriacaoTabela")]
    partial class CriacaoTabela
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cadastro_lojas_fullstack.DTO.DemandaDto", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApelidoLoja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ArquitetoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArquitetoId");

                    b.ToTable("Demandas", (string)null);
                });

            modelBuilder.Entity("cadastro_lojas_fullstack.Models.ArquitetoDto", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("ativo")
                        .HasColumnType("tinyint");

                    b.Property<string>("cnpjArquiteto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dataContratacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dataDesligamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("emailArquiteto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeArquiteto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Arquitetos", (string)null);
                });

            modelBuilder.Entity("cadastro_lojas_fullstack.DTO.DemandaDto", b =>
                {
                    b.HasOne("cadastro_lojas_fullstack.Models.ArquitetoDto", "ArquitetoDto")
                        .WithMany("Demandas")
                        .HasForeignKey("ArquitetoId");

                    b.Navigation("ArquitetoDto");
                });

            modelBuilder.Entity("cadastro_lojas_fullstack.Models.ArquitetoDto", b =>
                {
                    b.Navigation("Demandas");
                });
#pragma warning restore 612, 618
        }
    }
}
